# Generated by Django 4.0.3 on 2022-04-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_dep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_earning',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
