# Generated by Django 4.0.3 on 2022-04-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_active_dep_user_total_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation',
            field=models.CharField(blank=True, default=0.0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.CharField(blank=True, default=0.0, max_length=20, null=True),
        ),
    ]
